// Auto-generated by Supabase CLI: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.types.ts
// Placeholder types — akan di-replace bila awak setup Supabase project

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          role: 'student' | 'class_teacher' | 'discipline_teacher' | 'counselor' | 'admin' | 'parent'
          full_name: string
          class_name: string | null
          ic_or_student_id: string | null
          avatar_url: string | null
          parent_id: string | null
          must_change_password: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      checkins: {
        Row: {
          id: string
          student_id: string
          checkin_date: string
          q1_kehadiran_ketepatan: number | null
          q2_pematuhan_peraturan: number | null
          q3_penyiapan_tugasan: number | null
          q4_kebersihan: number | null
          q5_komunikasi_sopan: number | null
          q6_motivasi_belajar: number | null
          q7_perasaan_emosi: 'gembira' | 'sedih' | 'tertekan' | 'biasa' | null
          q8_hubungan_rakan: number | null
          q9_tahap_stres: number | null
          q10_perlukan_bantuan: 'ya' | 'tidak' | 'mungkin' | null
          discipline_score: number | null
          emotional_score: number | null
          total_score: number | null
          created_at: string
        }
        Insert: Omit<
          Database['public']['Tables']['checkins']['Row'],
          'id' | 'created_at' | 'total_score' | 'discipline_score' | 'emotional_score'
        >
        Update: Partial<Database['public']['Tables']['checkins']['Insert']>
      }
      risk_levels: {
        Row: {
          id: string
          student_id: string
          level: 'hijau' | 'kuning' | 'jingga' | 'merah'
          reason: string | null
          calculated_at: string
          is_active: boolean
        }
        Insert: Omit<Database['public']['Tables']['risk_levels']['Row'], 'id' | 'calculated_at'>
        Update: Partial<Database['public']['Tables']['risk_levels']['Insert']>
      }
      behavior_records: {
        Row: {
          id: string
          student_id: string
          record_type: 'attendance' | 'discipline_case' | 'merit' | 'cocurricular' | 'teacher_note' | 'self_reflection'
          description: string | null
          points: number
          recorded_by: string | null
          record_date: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['behavior_records']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['behavior_records']['Insert']>
      }
      intervention_records: {
        Row: {
          id: string
          student_id: string
          counselor_id: string
          session_date: string
          intervention_type: string | null
          objective: string | null
          summary: string | null
          follow_up_action: string | null
          case_status: 'baru' | 'dalam_tindakan' | 'susulan' | 'selesai' | 'rujuk_luar'
          referral_to: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['intervention_records']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['intervention_records']['Insert']>
      }
      badges: {
        Row: {
          id: string
          name: string
          description: string | null
          icon_url: string | null
          criteria: string | null
        }
        Insert: Omit<Database['public']['Tables']['badges']['Row'], 'id'>
        Update: Partial<Database['public']['Tables']['badges']['Insert']>
      }
      student_badges: {
        Row: {
          id: string
          student_id: string
          badge_id: string
          earned_at: string
        }
        Insert: Omit<Database['public']['Tables']['student_badges']['Row'], 'id' | 'earned_at'>
        Update: Partial<Database['public']['Tables']['student_badges']['Insert']>
      }
      points_tracker: {
        Row: {
          student_id: string
          total_points: number
          current_streak: number
          longest_streak: number
          last_checkin_date: string | null
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['points_tracker']['Row'], 'updated_at'>
        Update: Partial<Database['public']['Tables']['points_tracker']['Insert']>
      }
      counseling_sessions: {
        Row: {
          id: string
          student_id: string
          counselor_id: string | null
          session_date: string
          session_time: string
          purpose: string | null
          status: 'pending' | 'disahkan' | 'selesai' | 'dibatalkan'
          reminder_sent: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['counseling_sessions']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['counseling_sessions']['Insert']>
      }
      reach_out_messages: {
        Row: {
          id: string
          student_id: string
          sender_id: string
          message: string
          source: 'murid' | 'ibu_bapa' | 'refleksi'
          status: 'baru' | 'dibaca' | 'dijawab' | 'ditutup'
          checkin_id: string | null
          counselor_id: string | null
          reply_message: string | null
          replied_at: string | null
          created_at: string
          updated_at: string
          student_seen_reply: boolean
        }
        Insert: Omit<Database['public']['Tables']['reach_out_messages']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['reach_out_messages']['Insert']>
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: 'reminder_checkin' | 'reminder_session' | 'alert_no_checkin' | 'motivational_message' | 'alert_risk_change'
          message: string
          is_read: boolean
          sent_at: string
        }
        Insert: Omit<Database['public']['Tables']['notifications']['Row'], 'id' | 'sent_at'>
        Update: Partial<Database['public']['Tables']['notifications']['Insert']>
      }
    }
    Views: {}
    Functions: {
      get_user_role: {
        Returns: 'student' | 'class_teacher' | 'discipline_teacher' | 'counselor' | 'admin' | 'parent'
      }
      is_staff: {
        Returns: boolean
      }
      is_counselor_or_admin: {
        Returns: boolean
      }
      is_parent_of: {
        Args: { student_uuid: string }
        Returns: boolean
      }
      is_class_teacher_of: {
        Args: { student_uuid: string }
        Returns: boolean
      }
    }
    Enums: {
      user_role: 'student' | 'class_teacher' | 'discipline_teacher' | 'counselor' | 'admin' | 'parent'
      risk_level: 'hijau' | 'kuning' | 'jingga' | 'merah'
      record_type: 'attendance' | 'discipline_case' | 'merit' | 'cocurricular' | 'teacher_note' | 'self_reflection'
      case_status: 'baru' | 'dalam_tindakan' | 'susulan' | 'selesai' | 'rujuk_luar'
      session_status: 'pending' | 'disahkan' | 'selesai' | 'dibatalkan'
      notification_type: 'reminder_checkin' | 'reminder_session' | 'alert_no_checkin' | 'motivational_message' | 'alert_risk_change'
      emotion_type: 'gembira' | 'sedih' | 'tertekan' | 'biasa'
      need_help: 'ya' | 'tidak' | 'mungkin'
      reach_out_source: 'murid' | 'ibu_bapa' | 'refleksi'
      reach_out_status: 'baru' | 'dibaca' | 'dijawab' | 'ditutup'
    }
  }
}
